---
# select the first dbserver as our server.  we'll only have one for now anyway
mysqldbserver: "{{ groups['dbserver'][0] }}"
mongodbserver: "{{ groups['dbserver'][0] }}"
# password for the mysql server
mysqlpassword: "{{ lookup('password','credentials/mysqlpassword chars=ascii_letters,digits') }}"
# password for the mongodb user
mongodbpassword: "{{ lookup('password','credentials/mongodbpassword chars=ascii_letters,digits') }}"
# root server name
servername: live.driveshare.org
# private nodes addresses.  if you have private networking, the nodes private 
# addresses should be put as a list here.  by default, these are the same as the
# public ip addresses
# privatenodes: "{{ groups['nodes'] }}"
privatenodes: "{{ hostvars|map(attribute='ansible_eth1')|map(attribute='address')|list }}"
# pull the ip address for the loadbalancer
lbaddr: "{{ hostvars[groups['loadbalancer'][0]]['ansible_default_ipv4']['address'] }}"
# whether to globally enable ssl (this will enable ssl on the dashboard and the nodes.)
# the load balancer by default is configured to passthrough https requests
ssl_enabled: True
# will need these if ssl is enabled
certificate_src: files/example.crt
certificate_dest: /etc/ssl/certs/example.crt
certificate_key_src: files/example.key
certificate_key_dest: /etc/ssl/private/example.key
dhparam_src: files/dh4096.pem
dhparam_dest: /etc/ssl/certs/dh4096.pem