---
lbproxies: "{{ privatenodes }}"
# this is the port exposed on the public side of the load balancer
lbport: "{{ 8443 if ssl_enabled else 800 }}"
# this is the port the nodes have exposed that the load balancer is directing requests to
proxyport: "{{ 14443 if ssl_enabled else 8000 }}"
# this is whether the load balancer should decrypt ssl traffic before passing it on
lbssl_enabled: "{{ ssl_enabled }}"
# this is whether the nodes have ssl enabled and should be connected to with https
proxyssl_enabled: "{{ ssl_enabled }}"
