---  
- name: Install nginx
  apt: pkg={{ item }} state=latest
  with_items:
    - nginx
    
- name: Remove default nginx config
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: Restart nginx
  
- name: Ensure nginx is running
  service: name=nginx state=running
