---
- name: Install mysql
  hosts: dbservers
  remote_user: root
  
  roles:
    - common
    - dsnodedb


- name: Install downstream-node
  hosts: nodes
  remote_user: root
  
  roles:
    - common
    - dsnode
    