---
- name: Install mysql
  hosts: dbservers
  remote_user: root
  sudo: true
  
  roles:
    - dsnodedb


- name: Install downstream-node
  hosts: nodes
  remote_user: root
  sudo: true
  
  roles:
    - dsnode

- name: Install load balancer
  hosts: load balancer
  remote_user: root
  sudo: true
  
  roles:
    - nginxlb