---
- name: Install load balancer
  hosts: loadbalancer
  remote_user: root
  sudo: true
  
  roles:
    - nginxlb

- name: Install mysql
  hosts: dbserver
  remote_user: root
  sudo: true
  
  roles:
    - dsnodedb

- name: Install downstream-node
  hosts: nodes
  remote_user: root
  sudo: true
  
  roles:
    - dsnode
    
- name: Install downstream-dash
  hosts: dashboards
  remote_user: root
  sudo: true
  
  roles:
    - dsdash