---
 - name: Restart uwsgi
   service: name=uwsgi state=restarted

 - name: Restart node maintain
   service: name=node-maintain state=restarted
   
 - name: Regenerate chunks
   command: "{{dsnodeenv}}/bin/python {{dsnodeprojroot}}/runapp.py --clearchunks"
   when: inventory_hostname in groups['dbserver']
   
 - name: Regenerate heartbeat
   file: path={{dsnodedataroot}}/heartbeat state=absent
   when: inventory_hostname in groups['dbserver']