--- 
- name: Setup the database
  mysql_db: name=downstream
  
# this should probably be in mysql and be configurable but for now we'll leave it here.
- name: Configure mysql to listen to outside servers
  lineinfile: dest=/etc/mysql/my.cnf regexp="bind-address" line="bind-address = 0.0.0.0"
  notify: Restart mysql