---
- name: Setup the database
  mysql_db: name=downstream
  
# this should probably be in mysql and be configurable but for now we'll leave it here.
- name: Configure mysql to listen to outside servers
  lineinfile: dest=/etc/mysql/my.cnf regexp="bind-address" line="bind-address = 0.0.0.0"
  notify: Restart mysql
  
- name: Configure mongodb to listen to outside servers
  lineinfile: dest=/etc/mongodb.conf regexp="bind_ip" line="bind_ip = 0.0.0.0"
  notify: Restart mongodb

- name: Copy cron job for cleaning db hourly
  copy: dest=/etc/cron.hourly/clean src=downstream.sh owner=root mode=0755
