---
- name: Install prerequisites
  apt: pkg={{ item }} state=latest
  with_items:
    - mysql-server

- name: Install virtualenv
  pip: name=virtualenv
    
- name: Setup the database
  mysql_db: name=downstream

- name: Setup the database user
  mysql_user: name=downstream password="{{ mysqlpassword }}" priv=downstream.*:ALL