---
- name: Install prerequisites
  apt: pkg={{ item }} state=latest
  with_items:
    - mysql-server

- name: Install virtualenv
  pip: name=virtualenv
    
- name: Setup the database
  mysql_db: name=downstream
  
- name: Configure mysql to listen to outside servers
  lineinfile: dest=/etc/mysql/my.cnf regexp="bind-address" line="bind-address = 0.0.0.0"
