---
# downstream node directory: the installation directory
dsnodeuser: dsnode
dsnodeuserroot: /home/{{dsnodeuser}}
dsnodeprojroot: {{dsnodeuserroot}}/downstream-node
dsnodelibroot: {{dsnodeprojroot}}/downstream_node
dsnodedataroot: {{dsnodeprojroot}}/data
dsnodegeodbpath: {{dsnodedataroot}}/GeoLite2-City.mmdb
dsnoderepourl: https://github.com/storj/downstream-node.git
dsnodemaxminddburl: http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz
dsnodewhitelistrepourl: https://github.com/storj/whitelist.git
dsnodewhitelistroot: {{dsnodedataroot}}/whitelist
dsnodewhitelistfile: {{dsnodewhitelistroot}}/storj_crowdfunding_by_amount.txt