---
- name: Update apt
  apt: update_cache=yes

- name: Install prerequisites
  apt: pkg={{ item }} state=latest
  with_items:
    - mysql-server
    - libcrypto++-dev    
    - libgmp-dev
    - python-mysqldb
    - git
    - python-pip
    - python-dev

- name: Install virtualenv
  pip: name=virtualenv
    
- name: Setup the database
  mysql_db: name=downstream

- name: Setup the database user
  mysql_user: name=downstream password="{{ lookup('password', 'credentials/mysqlpassword') }}" priv=downstream.*:ALL
  
- name: Set up the downstream-node user
  user: name={{ dsnodeuser }}

- name: Clone downstream-node repo
  git: repo={{dsnoderepourl}} dest={{dsnodeprojroot}}

- name: Create data directory
  file: path={{dsnodedataroot}} state=directory

- stat: path={{dsnodegeodbpath}}
  register: st
  
- name: Pull in geolocation database and unzip
  command: "{{item}}"
  with_items:
    - curl -o {{dsnodegeodbpath}}.gz {{dsnodemaxminddburl}}
    - gunzip {{dsnodegeodbpath}}.gz
  when: st.stat.isreg is not defined or not st.stat.isreg
  
- name: Copy downstream-node config
  template: src=config.py dest={{dsnodelibroot}}/config.py

- name: Install downstream-node
  pip: requirements={{dsnodeprojroot}}/requirements.txt virtualenv={{dsnodeuserroot}}/.env
  
- name: Initialize database
  command: python {{dsnodeprojroot}}/runapp.py --initdb

- name: Clone whitelist
  git: repo={{dsnodewhitelistrepourl}} dest={{dsnodewhitelistroot}}
  
- name: Initialize whitelist
  command: python {{dsnodeprojroot}}/runapp.py --whitelist {{dsnodewhitelistfile}}
  
- name: Start downstream-node
  command: nohup python {{dsnodeprojroot}}/runapp.py &
